### register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "nom": "new user",
    "email": "newuser4@gmail.com",
    "password": "1234"
}

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "newuser3@gmail.com",
    "password": "1234"
}

### get the current user
GET http://localhost:3000/auth/me