### register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "nom": "wail koundi",
    "email": "wail@gmail.com",
    "password": "1234"
}

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "wail@gmail.com",
    "password": "1234"
}