### get all users
GET http://localhost:3000/categories

### get a user by id
GET http://localhost:3000/categories/12

### add new user
POST http://localhost:3000/categories
Content-Type: application/json

{
    "nom": "new categorie"
}

### update an article
PATCH http://localhost:3000/categories/1
Content-Type: application/json

{
    "nom": "fashion"
}

### delete an article
DELETE http://localhost:3000/categories/3