### get all users
GET http://localhost:3000/users

### get a user by id
GET http://localhost:3000/users/1

### add new user
POST http://localhost:3000/users
Content-Type: application/json

{
    "nom": "new user",
    "email": "new.user@gmail.com",
    "password": "1234",
    "role": "AUTHOR"
}

### update a user
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
    "nom": "yazid hakimi",
    "password": "123456"
}

### delete an article
DELETE http://localhost:3000/users/1